 export const colors =
 [{attribute: "color", value: "Gold",                                      label: "Gold"},                                            
 {attribute: "color", value: "Dark Blue",                                 label: "Dark Blue"},                                          
 {attribute: "color", value: "Lilac",                                     label: "Lilac"},                                          
 {attribute: "color", value: "Orange",                                    label: "Orange"},                                          
 {attribute: "color", value: "Light Brown",                               label: "Light Brown"},                                          
 {attribute: "color", value: "Yellow",                                    label: "Yellow"},                                          
 {attribute: "color", value: "Tan",                                       label: "Tan"},                                          
 {attribute: "color", value: "Wheaten",                                   label: "Wheaten"},                                          
 {attribute: "color", value: "White",                                     label: "White"},                                          
 {attribute: "color", value: "Dark Brown",                                label: "Dark Brown"},                                          
 {attribute: "color", value: "Blue",                                      label: "Blue"},                                          
 {attribute: "color", value: "Light Silver",                              label: "Light Silver"},                                          
 {attribute: "color", value: "Red",                                       label: "Red"},                                          
 {attribute: "color", value: "Cream",                                     label: "Cream"},                                          
 {attribute: "color", value: "Black",                                     label: "Black"},                                          
 {attribute: "color", value: "Silver",                                    label: "Silver"},                                         
 {attribute: "color", value: "Rust",                                      label: "Rust"},                                          
 {attribute: "color", value: "Brown",                                     label: "Brown"},                                          
 {attribute: "color", value: "Apricot",                                   label: "Apricot"},                                          
 {attribute: "color", value: "Fawn",                                      label: "Fawn"},                                          
 {attribute: "color", value: "Chestnut",                                  label: "Chestnut"},                                          
 {attribute: "color", value: "Gray",                                      label: "Gray"},                                          
 {attribute: "color", value: "Beige",                                     label: "Beige"},                                          
 {attribute: "color", value: "Dark Brown and Gold Striped",               label: "Dark Brown and Gold Striped"},                                          
 {attribute: "color", value: "Black Brown Brindle",                       label: "Black Brown Brindle"},                                          
 {attribute: "color", value: "Black and Tan Striped",                     label: "Black and Tan Striped"},                                          
 {attribute: "color", value: "Blue and Apricot Striped",                  label: "Blue and Apricot Striped"},                                          
 {attribute: "color", value: "Dark Brown and Light Brown Striped",        label: "Dark Brown and Light Brown Striped"},                                          
 {attribute: "color", value: "Dark Brown and Apricot Striped",            label: "Dark Brown and Apricot Striped"},                                          
 {attribute: "color", value: "Black and Apricot Striped",                 label: "Black and Apricot Striped"},                                          
 {attribute: "color", value: "Dark Brown and Tan Striped",                label: "Dark Brown and Tan Striped"},                                          
 {attribute: "color", value: "Black and Light Brown Striped",             label: "Black and Light Brown Striped"},                                          
 {attribute: "color", value: "White, Dark Brown, and Light Brown Striped",label: "White, Dark Brown, and Light Brown Striped"},                                          
 {attribute: "color", value: "White, Black, and Light Brown Striped",     label: "White, Black, and Light Brown Striped"},                                          
 {attribute: "color", value: "White, Dark Brown, and Tan Striped",        label: "White, Dark Brown, and Tan Striped"},                                          
 {attribute: "color", value: "White, Black, and Tan Striped",             label: "White, Black, and Tan Striped"},                                          
 {attribute: "color", value: "White, Black, and Brown Striped",           label: "White, Black, and Brown Striped"},                                          
 {attribute: "color", value: "Black, Dark Brown, and Tan Striped",        label: "Black, Dark Brown, and Tan Striped"},                                          
 {attribute: "color", value: "White, Black, and Dark Brown Striped",      label: "White, Black, and Dark Brown Striped"},                                          
 {attribute: "color", value: "White and Red Dotted",                      label: "White and Red Dotted"},                                          
 {attribute: "color", value: "White and Orange Dotted",                   label: "White and Orange Dotted"},                                          
 {attribute: "color", value: "Black and White Dotted",                    label: "Black and White Dotted"},                                          
 {attribute: "color", value: "White, Dark Blue, and Gold Dotted",         label: "White, Dark Blue, and Gold Dotted"},                                          
 {attribute: "color", value: "Black and Tan",                             label: "Black and Tan"},                                          
 {attribute: "color", value: "Dark Blue and Gold",                        label: "Dark Blue and Gold"},                                          
 {attribute: "color", value: "White and Gold",                            label: "White and Gold"},                                          
 {attribute: "color", value: "Black and Cream",                           label: "Black and Cream"},                                          
 {attribute: "color", value: "White and Chestnut",                        label: "White and Chestnut"},                                          
 {attribute: "color", value: "Black and Orange",                          label: "Black and Orange"},                                          
 {attribute: "color", value: "White and Dark Brown",                      label: "White and Dark Brown"},                                          
 {attribute: "color", value: "Blue and Fawn",                             label: "Blue and Fawn"},                                          
 {attribute: "color", value: "Tan and Apricot",                           label: "Tan and Apricot"},                                          
 {attribute: "color", value: "White and Light Silver",                    label: "White and Light Silver"},                                          
 {attribute: "color", value: "Brown and Tan",                             label: "Brown and Tan"},                                          
 {attribute: "color", value: "Gray and Gold",                             label: "Gray and Gold"},                                          
 {attribute: "color", value: "Silver and Beige",                          label: "Silver and Beige"},                                          
 {attribute: "color", value: "Black and Rust",                            label: "Black and Rust"},                                          
 {attribute: "color", value: "Dark Brown and Tan",                        label: "Dark Brown and Tan"},                                          
 {attribute: "color", value: "Lilac and Orange",                          label: "Lilac and Orange"},                                          
 {attribute: "color", value: "Black and Chestnut",                        label: "Black and Chestnut"},                                          
 {attribute: "color", value: "White and Brown",                           label: "White and Brown"},                                          
 {attribute: "color", value: "White and Red",                             label: "White and Red"},                                          
 {attribute: "color", value: "Black and Gold",                            label: "Black and Gold"},                                          
 {attribute: "color", value: "White and Tan",                             label: "White and Tan"},                                          
 {attribute: "color", value: "Light Brown and Gold",                      label: "Light Brown and Gold"},                                          
 {attribute: "color", value: "Blue and Gold",                             label: "Blue and Gold"},                                          
 {attribute: "color", value: "White and Yellow",                          label: "White and Yellow"},                                          
 {attribute: "color", value: "Light Silver and Dark Blue",                label: "Light Silver and Dark Blue"},                                          
 {attribute: "color", value: "White and Silver",                          label: "White and Silver"},                                          
 {attribute: "color", value: "White and Blue",                            label: "White and Blue"},                                          
 {attribute: "color", value: "Rust and Gold",                             label: "Rust and Gold"},                                          
 {attribute: "color", value: "Gray and Black",                            label: "Gray and Black"},                                          
 {attribute: "color", value: "Black and Wheaten",                         label: "Black and Wheaten"},                                          
 {attribute: "color", value: "White and Orange",                          label: "White and Orange"},                                          
 {attribute: "color", value: "Black and Light Brown",                     label: "Black and Light Brown"},                                          
 {attribute: "color", value: "White and Dark Blue",                       label: "White and Dark Blue"},                                          
 {attribute: "color", value: "Dark Brown and Gold",                       label: "Dark Brown and Gold"},                                          
 {attribute: "color", value: "White and Black",                           label: "White and Black"},                                          
 {attribute: "color", value: "Light Brown and Fawn",                      label: "Light Brown and Fawn"},                                          
 {attribute: "color", value: "Blue and Apricot",                          label: "Blue and Apricot"},                                          
 {attribute: "color", value: "Gold and Yellow",                           label: "Gold and Yellow"},                                          
 {attribute: "color", value: "White and Rust",                            label: "White and Rust"},                                          
 {attribute: "color", value: "Black and Fawn",                            label: "Black and Fawn"},                                          
 {attribute: "color", value: "White and Apricot",                         label: "White and Apricot"},                                          
 {attribute: "color", value: "Silver and Black",                          label: "Silver and Black"},                                          
 {attribute: "color", value: "White and Fawn",                            label: "White and Fawn"},                                          
 {attribute: "color", value: "Lilac and Apricot",                         label: "Lilac and Apricot"},                                          
 {attribute: "color", value: "Apricot and Cream",                         label: "Apricot and Cream"},                                          
 {attribute: "color", value: "White and Beige",                           label: "White and Beige"},                                          
 {attribute: "color", value: "Blue and Dark Blue",                        label: "Blue and Dark Blue"},                                          
 {attribute: "color", value: "White and Lilac",                           label: "White and Lilac"},                                          
 {attribute: "color", value: "White and Light Brown",                     label: "White and Light Brown"},                                          
 {attribute: "color", value: "White and Gray",                            label: "White and Gray"},                                          
 {attribute: "color", value: "Black and Dark Brown",                      label: "Black and Dark Brown"},                                          
 {attribute: "color", value: "Black and Beige",                           label: "Black and Beige"},                                          
 {attribute: "color", value: "White, Gray, and Black",                    label: "White, Gray, and Black"},                                          
 {attribute: "color", value: "White, Black, and Apricot",                 label: "White, Black, and Apricot"},                                          
 {attribute: "color", value: "White, Light Brown, and Tan",               label: "White, Light Brown, and Tan"},                                          
 {attribute: "color", value: "White, Dark Blue, and Apricot",             label: "White, Dark Blue, and Apricot"},                                          
 {attribute: "color", value: "White, Black, and Light Brown",             label: "White, Black, and Light Brown"},                                          
 {attribute: "color", value: "White, Black, and Beige",                   label: "White, Black, and Beige"},                                          
 {attribute: "color", value: "White, Dark Brown, and Gold",               label: "White, Dark Brown, and Gold"},                                          
 {attribute: "color", value: "White, Silver, and Black",                  label: "White, Silver, and Black"},                                          
 {attribute: "color", value: "White, Gray, and Gold",                     label: "White, Gray, and Gold"},                                          
 {attribute: "color", value: "White, Black, and Orange",                  label: "White, Black, and Orange"},                                          
 {attribute: "color", value: "White, Black, and Rust",                    label: "White, Black, and Rust"},                                          
 {attribute: "color", value: "White, Dark Blue, and Tan",                 label: "White, Dark Blue, and Tan"},                                          
 {attribute: "color", value: "White, Dark Blue, and Beige",               label: "White, Dark Blue, and Beige"},                                          
 {attribute: "color", value: "White, Black, and Fawn",                    label: "White, Black, and Fawn"},                                          
 {attribute: "color", value: "White, Black, and Gold",                    label: "White, Black, and Gold"},                                          
 {attribute: "color", value: "Blue, Black, and Yellow",                   label: "Blue, Black, and Yellow"},                                          
 {attribute: "color", value: "White, Silver, and Beige",                  label: "White, Silver, and Beige"},                                          
 {attribute: "color", value: "White, Lilac, and Dark Blue",               label: "White, Lilac, and Dark Blue"},                                          
 {attribute: "color", value: "White, Black, and Tan",                     label: "White, Black, and Tan"},                                          
 {attribute: "color", value: "Silver, Black, and Gold",                   label: "Silver, Black, and Gold"},                                          
 {attribute: "color", value: "White, Black, and Dark Brown",              label: "White, Black, and Dark Brown"},                                          
 {attribute: "color", value: "White, Light Silver, and Dark Blue",        label: "White, Light Silver, and Dark Blue"}]                                          